spring:
  datasource:                                     # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource      # 数据源的类型，可以更改为其他的数据源配置，比如druid
    driver-class-name: com.mysql.cj.jdbc.Driver      # mysql/MariaDB 的数据库驱动类名称
    url: jdbc:mysql://192.168.2.201:3306/hire-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    hikari:
      connection-timeout: 30000               # 等待连接池分配连接的最大时间（毫秒），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                         # 最小连接数
      maximum-pool-size: 20                   # 最大连接数
      auto-commit: true                       # 自动提交
      idle-timeout: 600000                    # 连接超时的最大时长（毫秒），超时则会被释放（retired）
      pool-name: DataSourceHikariCP           # 连接池的名字
      max-lifetime: 18000000                  # 连接池的最大生命时长（毫秒），超时则会被释放（retired）
      connection-test-query: SELECT 1
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.201:8848
  rabbitmq:
    host: 192.168.2.202
    port: 5672
    virtual-host: /
    username: hanxin
    password: hanxin
    publisher-confirm-type: correlated
    listener:
     simple:
       acknowledge-mode: manual
#        prefetch: 2 # 每次每个消费者从mq中拉取的消息数量，直到手动ack确认后才会继续拉取
seata:
    enabled: true
    tx-service-group: hanxin_tx_group
    service:
      vgroup-mapping:
        hanxin_tx_group: SEATA_GROUP
      grouplist:
        SEATA_GROUP: 192.168.2.202:8091
    config:
      nacos:
        server-addr: 192.168.2.201:8848
        username: nacos
        password: nacos
    registry:
      nacos:
        server-addr: 192.168.2.201:8848
        username: nacos
        password: nacos